<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev
 * Date: 6/27/17
 * Time: 11:49 AM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'course_item' => array('label' => $this->truncate($user->getTitle(), 15), 'link' => $user->getHref()),
        'testing_create' => array('label' => 'EDIT_PROFILE_PAGE', 'active' => true)
    ))
    ->setTitle('EDIT_PROFILE_PAGE')
//    ->setDescription('Обучение на платформе является бесплатным для студентов. ')
;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">
                <div class="row m-b-md flash-messenger">
                    <div class="col-sm-12 ">
                        <?php
                        echo $this->flashMessenger()
                            ->setMessageOpenFormat('<div class="alert alert-danger"><p>')
                            ->setMessageSeparatorString('</p><p>')
                            ->setMessageCloseString('</p></div>')
                            ->renderCurrent('error');

                        echo $this->flashMessenger()
                            ->setMessageOpenFormat('<div class="alert alert-success"><p>')
                            ->setMessageSeparatorString('</p><p>')
                            ->setMessageCloseString('</p></div>')
                            ->renderCurrent('success');

                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
                        ?>
                    </div>
                </div>
                <?php echo $this->formRender()->render($form); ?>
            </div>
        </div>
    </div>
</div>
