<?php
/**
 * Created by PhpStorm.
 * User: ogismatulin
 * Date: 11.03.2018
 * Time: 16:39
 */

namespace User\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use User\Entity\UserUsers;


/**
 * PersonsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserUsersRepository extends EntityRepository
{
    public function findUsersSelect2($fullName = null)
    {
        $names = explode(' ', $fullName);
        $qb = $this->createQueryBuilder('u');
        $qb->setMaxResults(10);
        $count = 0;
        foreach ($names as $name) {
            $qb->orWhere('LOWER(u.fname) LIKE LOWER(:param' . $count . ')')
                ->setParameter('param' . $count, '%' . $name . '%');
            $qb->orWhere('LOWER(u.lname) LIKE LOWER(:param' . $count . ')')
                ->setParameter('param' . $count, '%' . $name . '%');
            $qb->orWhere('LOWER(u.pname) LIKE LOWER(:param' . $count . ')')
                ->setParameter('param' . $count, '%' . $name . '%');
            $count++;
        }

        /** @var UserUsers[] $users */
        $users = $qb->getQuery()->getResult();
        $result = array();
        foreach ($users as $user) {
            $result['results'][] = array(
                'id' => $user->getId(),
                'text' => $user->getFullName(),
            );
        }
        return $result;
    }
}