<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev@srs.lan
 * Date: 2/15/18
 * Time: 8:53 PM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'General Settings', 'active' => true)))
    ->setTitle('General Settings')
    ->setDescription('GENERAL_SETTINGS_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
    <div class="hpanel">
        <div class="panel-body">
            <?php echo $this->formRender()->render($form); ?>
        </div>
    </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#lang').change(function(){
            location.href= '?lang='+$(this).val();
        });
    });
</script>