<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev@srs.lan
 * Date: 2/15/18
 * Time: 8:53 PM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Mail Settings', 'active' => true)))
    ->setTitle('Mail Settings')
    ->setDescription('MAIL_SETTINGS_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
    <div class="hpanel">
        <div class="panel-body">
            <?php echo $this->formRender()->render($form); ?>
        </div>
    </div>
    </div>
</div>
