<?php
/**
 * About.kg
 *
 * @author azim
 * Date: 2/4/14
 * @license    http://www.about.kg/license/
 */
?>
<?php

$this->headScript()
    ->appendFile($this->basePath('externals/summernote/summernote.js'), 'text/javascript');

$this->headLink()
    ->appendStylesheet($this->basePath('externals/summernote/summernote.css'));

$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Mail Settings', 'active' => true)))
    ->setTitle('Mail Settings')
    ->setDescription('MAIL_SETTINGS_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">
                <?php echo $this->formRender()->render($form); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#mailtemplate_id').change(function(){
            location.href= '?mailtemplate_id='+$(this).val();
        });

        $('.summernote').summernote({
            tabsize: 2,
            height: 100,
            toolbar: [
                ['style', ['style']],
                ['fontsize', ['fontsize']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['insert', ['link', 'picture', 'hr']],
                ['table', ['table']]
            ],
        });
    });
</script>