<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev@srs.lan
 * Date: 2/19/18
 * Time: 11:38 AM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(
        [
            'first' => ['label' => 'Languages', 'link' => $this->url('languages')],
            'second' => ['label' => 'Add new Phrase', 'active' => true]
        ]
    )
    ->setTitle('Languages Create')
    ->setDescription('LANGUAGES_BROWSE_DESCRIPTION')
;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">
                <?php echo $this->formRender()->render($form); ?>
            </div>
        </div>
    </div>
</div>