<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev@srs.lan
 * Date: 2/18/18
 * Time: 6:41 PM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Languages', 'active' => true)))
    ->setTitle('Languages')
    ->setDescription('LANGUAGES_BROWSE_DESCRIPTION')
;
?>

<div class="row">
    <div class="col-lg-12">
        <form>
            <div class="hpanel">
                <div class="panel-body">
                    <div class="input-group">
                        <input class="form-control" placeholder="<?= $this->translate('Search phrases...')?>" type="text" name="query" value="<?= $query?>">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> <?= $this->translate('Search')?></button>
                            <a href="<?= $this->url('admin_languages', ['action' => 'create'])?>" class="btn btn-success"><i class="fa fa-plus"></i> <?= $this->translate('Add new phrase')?></a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">
                <div class="table-responsive project-list">
                    <?php if($items->getTotalItemCount() > 0):?>
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th><?= $this->translate('Key')?></th>
                                    <th><?= $this->translate('Options')?></th>
                                </tr>
                            </thead>
                            <?php foreach ($items as $item):?>
                                <tr>
                                    <td><?= $this->translate($item->getKey())?></td>

                                    <td>
                                        <a href="<?= $this->url('admin_languages', ['action' => 'edit', 'id' => $item->getTranslateKeyId()])?>">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </table>
                        <?php if($items->getPages()->pageCount > 1):?>
                            <div class="pull-right">
                                <?php echo $this->paginationControl($items, 'Sliding', 'pagination/pagination.phtml', array(
                                    'query' => array('query' => $query),
                                    'router' => 'admin_languages',
                                    'params' => array()
                                )); ?>
                            </div>
                        <?php endif;?>
                    <?php else:?>
                        <div class="panel-heading">
                            <div class="alert alert-warning">
                                <i class="fa fa-bolt"></i> <?php echo $this->translate('Users not yet added.');?>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>