<?php
/**
 * @var \User\Entity\UserUsers $item
 * @var $this \Reserve\Classes\PhpStormPhtmlHelper
 */
?>
<div class="row">
    <div class="col-lg-4">
        <?= $this->itemPhoto($item->getPhotoId(), 'thumb.icon', $item->getFullName(), ['class' => 'img-circle m-b m-t-md width-100', 'pin' => $item->getPin()])?>
    </div>
    <div class="col-lg-8">
        <div class="pull-right text-right">
            <div class="btn-group">
                <a href="<?= $this->url('user_general', ['action' => 'edit', 'id' => $item->getId()])?>" class="btn btn-default btn-xs">
                    <i class="fa fa-pencil"></i> <?= $this->translate('Edit')?>
                </a>
            </div>
        </div>
        <div class="clearfix"></div>
        <h3 class="text-center">
            <a href="<?= $this->url('person_profile', ['id' => $item->getId()])?>">
                <?= $item->getFullName()?>
            </a>
        </h3>
    </div>
</div>
<div class="clearfix"></div>

<h4><?= $this->translate('General Information')?></h4>

<div class="profile-user-info profile-user-info-striped">
    <div class="profile-info-row">
        <div class="profile-info-name"> <?= $this->translate('Pin')?> </div>

        <div class="profile-info-value">
            <span><?= $item->getPin()?></span>
        </div>
    </div>
    <div class="profile-info-row">
        <div class="profile-info-name"> <?= $this->translate('Lastname')?> </div>

        <div class="profile-info-value">
            <span><?= $item->getLname()?></span>
        </div>
    </div>
    <div class="profile-info-row">
        <div class="profile-info-name"> <?= $this->translate('Firstname')?> </div>

        <div class="profile-info-value">
            <span><?= $item->getFname()?></span>
        </div>
    </div>
    <div class="profile-info-row">
        <div class="profile-info-name"> <?= $this->translate('Patronymic')?> </div>

        <div class="profile-info-value">
            <span><?= $item->getPname()?></span>
        </div>
    </div>
    <div class="profile-info-row">
        <div class="profile-info-name"> <?= $this->translate('Birthdate')?> </div>

        <div class="profile-info-value">
            <span><?=$item->getBdateWithAge($this->translate('age'))?></span>
        </div>
    </div>
</div>

