<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev@srs.lan
 * Date: 2/18/18
 * Time: 6:33 PM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Permissions', 'active' => true)))
    ->setTitle('Permissions')
    ->setDescription('PERMISSIONS_SETTINGS_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">
                <?php echo $this->formRender()->render($form); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#level_id').change(function(){
            location.href= '<?= $this->url()?>?level_id='+$(this).val();
        })
    });
</script>