<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Evidence Research Institute')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('themes/styles/static_custom.css'))
            ->prependStylesheet($this->basePath('styles/style.css'))
            ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/helper.css'))
            ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css'))
            ->prependStylesheet($this->basePath('vendor-js/bootstrap/dist/css/bootstrap.css'))
            ->prependStylesheet($this->basePath('vendor-js/animate.css/animate.css'))
            ->prependStylesheet($this->basePath('vendor-js/fontawesome/css/font-awesome.css'))
            ->prependStylesheet($this->basePath('themes/styles/languages.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('scripts/homer.js'))
            ->prependFile($this->basePath('vendor-js/sparkline/index.js'))
            ->prependFile($this->basePath('vendor-js/iCheck/icheck.min.js'))
            ->prependFile($this->basePath('vendor-js/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor-js/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('vendor-js/jquery-ui/jquery-ui.min.js'))
            ->prependFile($this->basePath('vendor-js/jquery/dist/jquery.min.js'))
        ?>
    </head>
    <body class="landing-page">
        <!-- Simple splash screen-->
        <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
        <!--[if lt IE 7]>
        <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?= $this->url('home')?>" class="navbar-brand">
                        <img src="<?= $this->basePath('themes/images/logo_evidence.png')?>" alt="">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                <?= $this->translate('About us')?>
                                <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href=""><?= $this->translate('Our team')?></a>
                                </li>
                                <li>
                                    <a href=""><?= $this->translate('Mission and Values')?></a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                <?= $this->translate('Solutions')?>
                                <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href=""><?= $this->translate('Sociological research')?></a>
                                </li>
                                <li>
                                    <a href=""><?= $this->translate('Market research')?></a>
                                </li>
                                <li>
                                    <a href=""><?= $this->translate('Monitoring and Project Evaluation')?></a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="page-scroll" page-scroll href="#features"><?= $this->translate('Analytics')?></a></li>
                        <li><a class="page-scroll" page-scroll href="#team"><?= $this->translate('Training')?></a></li>
                        <li><a class="page-scroll" page-scroll href="#pricing"><?= $this->translate('News')?> </a></li>
                        <li><a href="<?= $this->url('contacts')?>"><?= $this->translate('Contacts')?>  </a></li>
                        <?= $this->languageSwitch()?>
                    </ul>
                </div>
            </div>
        </nav>
        <?= $this->content ?>

        <?= $this->inlineScript() ?>
    </body>
</html>
