<?= $this->doctype() ?>

<?php

$siteTitle = '';
$description = '';
$keywords = '';
?>

<html lang="<?= $this->lang?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->prepend($siteTitle)->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="Description" content="<?php echo $description; ?>">
    <meta name="Keywords" content="<?php echo $keywords; ?>">

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('styles/style.css'))
        ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/helper.css'))
        ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css'))
            ->prependStylesheet($this->basePath('vendor-js/bootstrap/dist/css/bootstrap.css'))
        ->prependStylesheet($this->basePath('vendor-js/fontawesome/css/font-awesome.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('scripts/index.js'))
        ->prependFile($this->basePath('scripts/bootstrap.min.js'))
        ->prependFile($this->basePath('scripts/jquery-ui.min.js'))
        ->prependFile($this->basePath('scripts/jquery.min.js'))
    ?>
</head>
<body class="blank">
<!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <?php echo  $this->content;?>

    <div class="login-container">
        <div class="row">
            <div class="col-md-12 text-center">
                <?php echo vsprintf($this->translate('%s company_copyright'), date('Y'))?>
            </div>
        </div>
    </div>

</body>
</html>
