<?php
$this->headScript()
    ->appendFile($this->basePath('externals/summernote/summernote.js'), 'text/javascript');

$this->headLink()
    ->appendStylesheet($this->basePath('externals/summernote/summernote.css'));

$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Articles', 'link' => $this->url('admin_articles')),
        'second' => array('label' => 'Articles Edit', 'active' => true)
    ))
    ->setTitle('Portal Pages Edit')
    ->setDescription('ARTICLES_EDIT_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">
                        <?php echo $this->formRender()->render($form); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>