<?php
/** @var \Article\Entity\ArticleArticles $item */
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Articles', 'active' => true)))
    ->setTitle('Articles')
    ->setDescription('ARTICLES_BROWSE_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">
                        <div class="btn-group">
                            <a href="<?= $this->url('admin_articles', ['action' => 'create'])?>" class="btn btn-success">
                                <i class="fa fa-plus"></i>
                                <?= $this->translate('Add New Article')?>
                            </a>
                        </div>

                        <div class="m-b"></div>

                        <?php if($items->getTotalItemCount() > 0):?>
                            <table class="table table-striped table-bordered table-hover ">
                                <thead>
                                    <tr>
                                        <th><?= $this->translate('ID')?></th>
                                        <th><?= $this->translate('Photo')?></th>
                                        <th><?= $this->translate('Title')?></th>
                                        <th><?= $this->translate('Creation Date')?></th>
                                        <th class="text-center"><?= $this->translate('Options')?></th>
                                    </tr>
                                </thead>
                                <?php foreach ($items as $item):?>
                                    <tr>
                                        <td><?= $item->getIdentity()?></td>
                                        <td>
                                            <?= $this->itemPhoto($item->getFileId(), 'thumb.icon', $item->getTitle(), ['class' => 'width-50'])?></td>
                                        <td><?= $item->getTitle()?></td>
                                        <td>
                                            <?= $this->dateFormat($item->getCreationDate(), IntlDateFormatter::MEDIUM)?>
                                        </td>
                                        <td class="text-center">
                                            <a href="<?= $this->url('admin_articles', ['action' => 'edit', 'id' => $item->getId()])?>">
                                                <i class="fa fa-pencil"></i>
                                            </a>

                                            <a class="confirm" href="<?= $this->url('admin_articles', ['action' => 'delete', 'id' => $item->getId()])?>">
                                                <i class="fa fa-trash red"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </table>
                            <?php if($items->getPages()->pageCount > 1):?>
                                <div class="pull-right">
                                    <?php echo $this->paginationControl($items, 'Sliding', 'pagination/pagination.phtml', array(
                                        'query' => array(),
                                        'router' => 'admin_articles',
                                        'params' => array()
                                    )); ?>
                                </div>
                            <?php endif;?>
                        <?php else:?>

                                <div class="alert alert-warning">
                                    <i class="fa fa-bolt"></i> <?php echo $this->translate('Pages not yet added.');?>
                                </div>

                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>