<?php
/**
 * Created by PhpStorm.
 * User: akazakbaev
 * Date: 6/30/17
 * Time: 12:19 PM
 */
?>
<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Users', 'active' => true)))
    ->setTitle('Users')
    ->setDescription('USER_BROWSE_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="panel-body">

                <div class="btn-group">
                    <a href="<?= $this->url('user_general', ['action' => 'create'])?>" class="btn btn-success">
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('Create User')?>
                    </a>
                </div>

                <div class="m-b"></div>

                <div class="table-responsive project-list">
                    <?php if($items->getTotalItemCount() > 0):?>
                        <table class="table table-striped table-bordered table-hover ">
                            <thead>
                            <tr>
                                <th><?= $this->translate('Full Name')?></th>
                                <th><?= $this->translate('Level')?></th>
                                <th><?= $this->translate('Status')?></th>
                                <th><?= $this->translate('State agency')?></th>
                                <th><?= $this->translate('Subdivision')?></th>
                                <th><?= $this->translate('Options')?></th>
                            </tr>
                            </thead>
                            <?php foreach ($items as $item):?>
                                <tr>
                                    <td><?= $item->getFullName()?></td>
                                    <td><?= $item->getLevel()->getTitle()?></td>
                                    <td><?= $item->getStatus() == \User\Entity\UserUsers::STATUS_ENABLED ? $this->translate('Enabled') : $this->translate('Disabled')?></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <a href="<?= $this->url('user_general', ['action' => 'edit', 'id' => $item->getId()])?>">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </table>
                        <?php if($items->getPages()->pageCount > 1):?>
                            <div class="pull-right">
                                <?php echo $this->paginationControl($items, 'Sliding', 'pagination/pagination.phtml', array(
                                    'query' => array(),
                                    'router' => 'user_general',
                                    'params' => array()
                                )); ?>
                            </div>
                        <?php endif;?>
                    <?php else:?>
                        <div class="panel-heading">
                            <div class="alert alert-warning">
                                <i class="fa fa-bolt"></i> <?php echo $this->translate('Users not yet added.');?>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>