<?php
$this->headScript()
    ->appendFile($this->basePath('externals/summernote/summernote.js'), 'text/javascript');

$this->headLink()
    ->appendStylesheet($this->basePath('externals/summernote/summernote.css'));

$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Portal Pages', 'link' => $this->url('pages_general')),
        'second' => array('label' => 'Portal Pages Edit', 'active' => true)
    ))
    ->setTitle('Portal Pages Edit')
    ->setDescription('PORTAL_PAGES_EDIT_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">


            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">
                        <?php echo $this->formRender()->render($form); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.summernote').summernote({
            tabsize: 2,
            height: 100,
            toolbar: [
                ['style', ['style']],
                ['fontsize', ['fontsize']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['insert', ['link', 'picture', 'hr']],
                ['table', ['table']]
            ],
        });
    });
</script>
