<?php
$this->pageBreadcrumbs()
    ->setItems(array(
        'first' => array('label' => 'Pages', 'active' => true)))
    ->setTitle('Pages')
    ->setDescription('PAGES_DESCRIPTION')
;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="hpanel">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">
                        <?php if($items->getTotalItemCount() > 0):?>
                            <table class="table table-striped table-bordered table-hover ">
                                <thead>
                                <tr>
                                    <th><?= $this->translate('Pages')?></th>
                                    <th><?= $this->translate('Options')?></th>
                                </tr>
                                </thead>
                                <?php foreach ($items as $item):?>
                                    <tr>
                                        <td><?= $item->getTitle(Locale::getDefault())?></td>
                                        <td>
                                            <a href="<?= $this->url('admin_pages', ['action' => 'edit', 'id' => $item->getId()])?>">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </table>
                            <?php if($items->getPages()->pageCount > 1):?>
                                <div class="pull-right">
                                    <?php echo $this->paginationControl($items, 'Sliding', 'pagination/pagination.phtml', array(
                                        'query' => array(),
                                        'router' => 'admin_pages',
                                        'params' => array()
                                    )); ?>
                                </div>
                            <?php endif;?>
                        <?php else:?>

                                <div class="alert alert-warning">
                                    <i class="fa fa-bolt"></i> <?php echo $this->translate('Pages not yet added.');?>
                                </div>

                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>